name: github metrics

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/metrics.yml
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency: 
  group: metrics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metrics-base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}

  metrics-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.GH_PAT }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: recently-used, most-used
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
          plugin_languages_details: percentage
